Direct2D-Initialize
itmo-engine-team/dream-engine pull request #10
Opened 2020-09-29 17:30 UTC by MMTsallagova

- Add Direct2D Initialize
- Change device flag - BGRA_Support
- Add 2D lib
- Add test text

2020-09-29 17:36 UTC, Jass2100 approved these changes

2020-09-29 17:42 UTC, nikchernyakov requested changes

2020-09-29 17:42 UTC, nikchernyakov commented on Engine/Graphics.cpp
> +    ID3D11Resource* res;
Какая-то странная логика разбиения строчек 
Объявление и получение ресурса должно быть вместе объединены (а они у тебя разделяются)
С surface тоже самое, у тебя объявление слито с ресурсом, а получение отдельно

2020-09-29 17:42 UTC, nikchernyakov commented on Engine/Graphics.cpp
> +    HRESULT rs = renderTarget->CreateSolidColorBrush(D2D1_COLOR_F{ 0.4f,1.0f,1.0f,1.0f }, &rBrush);
Описание цвета - Пробел после запятой, а перед/после скобочки не нужен

2020-09-29 17:42 UTC, nikchernyakov commented on Engine/Graphics.cpp
> +void Graphics::ConfigureBrush(FLOAT posX, FLOAT posY, const wchar_t* wszText_) // Configurate layout to text and brush to draw text
Комментарий строкой выше перенеси, у функций так вообще нельзя писать

2020-09-29 17:42 UTC, nikchernyakov commented on Engine/Graphics.h
>  #include <iostream>
Раздели include и pragma

2020-09-29 17:42 UTC, nikchernyakov commented on Engine/Graphics.h
> +    void BeginDraw() { renderTarget->BeginDraw(); }
А что за методы BeginDraw и EndDraw? Зачем они? Они же не используются нигде и смысла в них нет

2020-09-29 17:42 UTC, nikchernyakov commented on Engine/Graphics.h
> +    void ConfigureBrush(FLOAT posX, FLOAT posY, const wchar_t* wszText_);
Нужно разделить public и private методы, а также отделить методы Direct2d от остальных методов

2020-09-29 17:42 UTC, nikchernyakov commented on Engine/Graphics.h
>      ID3D11Texture2D* depthStencil = NULL;                     // Depth buffer texture
Null лучше заменить на nullptr

2020-09-29 17:42 UTC, nikchernyakov commented on Engine/Graphics.h
>      ID3D11Texture2D* depthStencil = NULL;                     // Depth buffer texture
И ниже также

2020-09-29 18:38 UTC, MMTsallagova commented on Engine/Graphics.h
> +    void ConfigureBrush(FLOAT posX, FLOAT posY, const wchar_t* wszText_);
Они все public, разве нет?

2020-09-29 18:43 UTC, nikchernyakov commented on Engine/Graphics.h
> +    void ConfigureBrush(FLOAT posX, FLOAT posY, const wchar_t* wszText_);
Ты нигде не используешь ConfigureBrush
К слову, вызов инициализации Direct2d можно перенести внутрь инициализации всего DirectX, потому что это его компонент внутренний по факту

2020-09-29 19:11 UTC, nikchernyakov requested changes

2020-09-29 19:11 UTC, nikchernyakov commented on Engine/Graphics.cpp
> +
Одна пустая строка разрыв между функциями должна быть

2020-09-29 19:11 UTC, nikchernyakov commented on Engine/Graphics.h
> +
Одна строка пустая строка разрыв должен быть

2020-09-29 19:11 UTC, nikchernyakov commented on Engine/Graphics.h
> +    IDWriteTextFormat* pTextFormat_;
Только заметил, мы же договорились переменные без префикса "p" именовать
И убери нижнее подчёркивание в конце имён плиз
Эта строка и выше, а также у тебя в методе выше есть такое

2020-09-29 19:11 UTC, nikchernyakov commented on Engine/Graphics.h
> +};
В конце перед скобкой должен быть отступ

2020-09-29 19:11 UTC, nikchernyakov commented on Engine/Graphics.h
> +    void ConfigureBrush(FLOAT posX, FLOAT posY, const wchar_t* wszText_);
Вот здесь последнюю переменную нужно пофиксить, убрать нижнее подчёркивание

2020-09-29 19:11 UTC, nikchernyakov commented on Engine/Graphics.h
> +    RECT rc;
Переименуй в rect, чтобы было очевиднее плиз

2020-09-29 19:11 UTC, nikchernyakov commented on Engine/Graphics.h
> +    ID2D1SolidColorBrush* rBrush = nullptr;
Убери r в начале плиз, чтобы brush было
Или в этом есть какая-то логика?

2020-09-30 08:31 UTC, nikchernyakov approved these changes

2020-09-30 08:33 UTC, merged