Added job systeam
itmo-engine-team/dream-engine pull request #23
Opened 2020-10-10 17:37 UTC by Jass2100

2020-10-10 21:00 UTC, MMTsallagova commented on Engine/JobSystem/JobSystem.cpp
> +		context* ctx;
отступы должны быть такими большими?

2020-10-10 21:00 UTC, MMTsallagova commented on Engine/JobSystem/JobSystem.h
> +        std::atomic<uint32_t> counter{ 0 };
Просто тут не такие огромные

2020-10-11 11:48 UTC, nikchernyakov requested changes

2020-10-11 11:48 UTC, nikchernyakov commented on Engine/JobSystem/JobSystem.cpp
> +		context* ctx;
Согласен, выделяются

2020-10-11 11:48 UTC, nikchernyakov commented on Engine/JobSystem/JobSystem.cpp
> +	inline bool work()
Метод с маленькой буквы. Он приватный?

2020-10-11 11:48 UTC, nikchernyakov commented on Engine/JobSystem/JobSystem.h
> +namespace JobSystem
А это не класс будет? Я с namespace не очень много работал. Как это будет выглядеть?
У нас это пространство одно будет на все места, где мы include сделаем?

2020-10-11 11:48 UTC, nikchernyakov commented on Engine/JobSystem/JobSystem.h
> +    void Dispatch(context& ctx, uint32_t jobCount, uint32_t groupSize, const std::function<void(JobArgs)>& task, size_t sharedmemory_size = 0);
У последней переменной нужно имя поменять

2020-10-11 11:48 UTC, nikchernyakov commented on Engine/JobSystem/JobSystem.h
> +    void* sharedmemory;		// stack memory shared within the current group (jobs within a group execute serially)
У последней переменной нужно имя поменять

2020-10-11 11:48 UTC, nikchernyakov commented on Engine/JobSystem/JobSystem.cpp
> +	void Dispatch(context& ctx, uint32_t jobCount, uint32_t groupSize, const std::function<void(JobArgs)>& task, size_t sharedmemory_size)
У последней переменной нужно имя поменять

2020-10-11 11:48 UTC, nikchernyakov commented on Engine/JobSystem/JobSystem.h
> +    struct context
Название структуры с маленькой буквы

2020-10-11 14:09 UTC, Jass2100 commented on Engine/JobSystem/JobSystem.cpp
> +		context* ctx;
Опять в визуалке отступы нормальные:(

2020-10-11 15:33 UTC, nikchernyakov requested changes

2020-10-11 15:33 UTC, nikchernyakov commented on Engine/JobSystem/JobSystem.cpp
> +        �ontext* ctx;
Опять C русская))0)

2020-10-11 15:36 UTC, Jass2100 commented on Engine/JobSystem/JobSystem.cpp
> +        �ontext* ctx;
))0)))000)

2020-10-11 15:53 UTC, nikchernyakov approved these changes

2020-10-11 15:54 UTC, MMTsallagova approved these changes

2020-10-11 15:54 UTC, merged