Added logger
itmo-engine-team/dream-engine pull request #3
Opened 2020-09-19 20:14 UTC by Jass2100

In this logger:
1)  DirectX handler (error and warning type).
2) Symple log (error and warning type).

2020-09-19 22:36 UTC, nikchernyakov requested changes

2020-09-19 22:36 UTC, nikchernyakov commented on ErrorLogger/ErrorLogger.cpp
> +	std::string error_message = GetDate();
А почему в таком формате имя переменной, а не errorMessage?

2020-09-19 22:36 UTC, nikchernyakov commented on ErrorLogger/ErrorLogger.cpp
> +	if (FAILED(hr))
Может лучше обратить if и делать им отсечку? Иначе слишком большой кусок кода в if расположен + создаётся лишняя вложеность. Может быть лучше сделать 
if (!FAILED(hr)){return;}

А дальше уже основной код?

2020-09-19 22:36 UTC, nikchernyakov commented on ErrorLogger/ErrorLogger.cpp
> +		error_message = GetDate();
Здесь тоже про имя переменной

2020-09-19 22:36 UTC, nikchernyakov commented on ErrorLogger/ErrorLogger.cpp
> +	case Error:
Я не знаю как в плюсах это делается, но разве для case не делается доп отступ?

2020-09-20 12:28 UTC, Jass2100 commented on ErrorLogger/ErrorLogger.cpp
> +	case Error:
По разному везде, я оставляю этот момент на автоматическое форматирование визуалкой и она так сама ставит. Могу сделать отступ.

2020-09-20 12:35 UTC, Jass2100 commented on ErrorLogger/ErrorLogger.cpp
> +	std::string error_message = GetDate();
Про переменную согласен.

2020-09-20 16:32 UTC, nikchernyakov approved these changes

2020-09-20 16:33 UTC, MMTsallagova approved these changes

2020-09-20 16:56 UTC, merged