Extend actor functional
itmo-engine-team/dream-engine pull request #31
Opened 2020-11-07 18:48 UTC by nikchernyakov

2020-11-07 18:52 UTC, Jass2100 requested changes

2020-11-07 18:52 UTC, Jass2100 commented on DreamEngine/Actor.h
> +    C FindComponent()
Может заменим на что-то букву C(component or componentClass). А то как то не очень читается)

2020-11-07 19:38 UTC, Jass2100 approved these changes

2020-11-08 09:26 UTC, MMTsallagova approved these changes

2020-11-08 11:58 UTC, merged