Shadow viewport
itmo-engine-team/dream-engine pull request #35
Opened 2020-11-12 08:13 UTC by MMTsallagova

2020-11-12 11:34 UTC, nikchernyakov requested changes

2020-11-12 11:34 UTC, nikchernyakov commented on DreamEngine/Graphics.h
> +    ID3D11ShaderResourceView* textureResourceView = nullptr;
В private переменные должны быть, взаимодействие через геттеры и сеттеры

2020-11-12 11:34 UTC, nikchernyakov commented on DreamEngine/MeshRenderer.cpp
> -ModelData* MeshRenderer::CreateQuardModel(ModelShader* shader, Vector3 quardSize)
Мне кажется, можно оставить, мало ли ещё когда-нибудь квадрат кому-нибудь понадобиться)
Только переименуй в SquareModel плиз

2020-11-12 15:43 UTC, Jass2100 approved these changes

2020-11-12 15:52 UTC, nikchernyakov requested changes

2020-11-12 15:52 UTC, nikchernyakov commented on DreamEngine/Graphics.h
>      bool editMode = false;
Не заметил видимо в прошлый раз и апрувнул , у тебя переменные ниже функций лежат. Не хорошо

2020-11-12 15:52 UTC, nikchernyakov commented on DreamEngine/Graphics.h
> +    void createShadowViewport();
Отступ перед фигурной скобкой

2020-11-12 15:53 UTC, MMTsallagova commented on DreamEngine/Graphics.h
>      bool editMode = false;
Я увидела это при исправлении, но почему-то местами не поменяла. Исправлюсь

2020-11-12 16:31 UTC, nikchernyakov requested changes

2020-11-12 16:31 UTC, nikchernyakov commented on DreamEngine/Graphics.h
> +    void createShadowViewport();
Отступ так и не появился или я запутался в красно зелёных строках?

2020-11-13 11:17 UTC, nikchernyakov approved these changes

2020-11-13 11:17 UTC, merged