Asset tree, Folder and Asset node
itmo-engine-team/dream-engine pull request #36
Opened 2020-11-12 15:53 UTC by Jass2100

2020-11-12 16:20 UTC, MMTsallagova commented on DreamEngine.Assets/FolderNode.h
> +
Лишние строчки?

2020-11-12 16:29 UTC, nikchernyakov requested changes

2020-11-12 16:29 UTC, nikchernyakov commented on DreamEngine.Assets/AssetNode.h
> +    friend class AssetTree;
А это правильно так размещать friend class? Я имею ввиду под конструктором? Если такого правила нет, я бы вынес это вверх и отделил бы от конструкторов, ибо теряется при беглом обзоре

2020-11-12 16:29 UTC, nikchernyakov commented on DreamEngine.Assets/AssetNode.h
> +    std::string NodeName;
Приватные переменные должны именоваться с маленькой буквы

2020-11-12 16:29 UTC, nikchernyakov commented on DreamEngine.Assets/AssetNode.h
> +};
Отступ перед фигурной скобкой

2020-11-12 16:29 UTC, nikchernyakov commented on DreamEngine.Assets/AssetNode.h
> +#include <string>
Мне кажется, надо взять за правило ещё, размещать более общие инклуды выше остального. То есть std библиотеку отделять и делать выше, чем инклуды из нашего движка

2020-11-12 16:29 UTC, nikchernyakov commented on DreamEngine.Assets/AssetServices.cpp
> +
Лишний отступ

2020-11-12 16:29 UTC, nikchernyakov commented on DreamEngine.Assets/AssetServices.cpp
>  std::vector<json> AssetServices::FindAssets()
А этот метод то тоже нужно привести к использованию нод
Надо сделать, чтобы он AssetTree возвращал

2020-11-12 16:29 UTC, nikchernyakov commented on DreamEngine.Assets/AssetServices.cpp
> +        remove(pathVar);
А куда денутся файлы если вот так вот сделать? Автоматически выше перейдут?

2020-11-12 16:29 UTC, nikchernyakov commented on DreamEngine.Assets/AssetServices.cpp
> +std::string AssetServices::CreatePath(FolderNode* fNode, std::string pastPath)
Неочевидное имя, так и не понял, что оно значит
Зачем вообще его передавать? Не легче просто передавать ноду, у которой мы хотим сделать путь, а не передавать каждый раз node->getName() вторым аргументом?

2020-11-12 16:29 UTC, nikchernyakov commented on DreamEngine.Assets/AssetServices.cpp
> +    path = fNode->GetNodeName() + "/" + path;
Где отличие ассета от папки?
Ассет же ещё должен оканчиваться ".asset", у тебя нигде вроде нет этого добавления

2020-11-12 16:29 UTC, nikchernyakov commented on DreamEngine.Assets/AssetServices.cpp
> +    if (fNode->GetParentNode() != nullptr)
Ааа, если ты передаёшь второй аргумент из-за рекурсии, то избавься от неё! Сделай просто проход с помощью while цикла

2020-11-12 16:29 UTC, nikchernyakov commented on DreamEngine.Assets/AssetServices.h
> +    std::string CreatePath(FolderNode* fNode, std::string pastPath);
Зачем делать такие сокращения? fNode. Лучше давай полными именами писать, выше ты же так и делаешь

2020-11-12 16:29 UTC, nikchernyakov commented on DreamEngine.Assets/AssetTree.h
> +//#include "AssetNode.h"
Комментарий можно удалить?

2020-11-12 16:29 UTC, nikchernyakov commented on DreamEngine.Assets/AssetTree.h
> +    static AssetTree  instance;
Тут два пробела

2020-11-12 16:29 UTC, nikchernyakov commented on DreamEngine.Assets/FolderNode.h
> +    std::vector<AssetNode*> ChildAssetList;
Не хватает отступа

2020-11-12 16:29 UTC, nikchernyakov commented on DreamEngine.Assets/FolderNode.h
> +    std::string NodeName;
Переменные с большой буквы

2020-11-12 16:29 UTC, nikchernyakov commented on DreamEngine.Assets/FolderNode.h
> +    friend class AssetTree;
Тот же вопрос по расположению friend class'а

2020-11-12 16:29 UTC, nikchernyakov commented on DreamEngine.Assets/FolderNode.h
> +#include "AssetNode.h"
То же предложение про инклуды

2020-11-12 16:29 UTC, nikchernyakov commented on DreamEngine.Assets/FolderNode.h
> +    std::vector<FolderNode*> GetChildFolderNode();
Не поменял имя функций, когда поменял имена переменных

2020-11-12 16:29 UTC, nikchernyakov commented on DreamEngine.Assets/FolderNode.h
> +    void setChildFolderNode(std::vector<FolderNode*> childNodes);
Лучше поменять название, ибо не понятно, что мы список передаём

2020-11-12 16:29 UTC, nikchernyakov commented on DreamEngine.Assets/FolderNode.cpp
> +    return  ChildFolderList;
Два пробела между словами

2020-11-12 16:29 UTC, nikchernyakov commented on DreamEngine.Assets/FolderNode.cpp
> +    return  ChildAssetList;
Два пробела между словами

2020-11-12 16:29 UTC, nikchernyakov commented on DreamEngine.Assets/FolderNode.h
> +
Переменные надо в private кинуть, чтобы AssetTree не имел к ним доступа на прямую

2020-11-12 16:29 UTC, nikchernyakov commented on DreamEngine.Assets/AssetNode.h
> +
Переменные надо в private кинуть, чтобы AssetTree не имел к ним доступа на прямую

2020-11-12 16:29 UTC, nikchernyakov commented on DreamEngine.Assets/FolderNode.h
> +    void setChildFolderNode(FolderNode* childNode);
Если ты что-то добавляешь, то должно быть имя Add, а то кажется, что ты заменяешь весь список или конкретную ноду

2020-11-12 16:29 UTC, nikchernyakov commented on DreamEngine.Assets/FolderNode.cpp
> +  auto iterator =  std::find(ChildFolderList.begin(), ChildFolderList.end(), childNode);
Отступы поехали, лишний пробел после = символа

2020-11-12 16:29 UTC, nikchernyakov commented on DreamEngine.Assets/AssetTree.h
> +    static FolderNode* rootnode;
rootNode надо сделать

2020-11-12 16:29 UTC, nikchernyakov commented on DreamEngine.Assets/AssetTree.cpp
> +AssetTree::AssetTree()
Конструктор лучше вверху прописывать

2020-11-12 16:29 UTC, nikchernyakov commented on DreamEngine.Assets/AssetTree.cpp
> +        for (FolderNode* fdNode : folderNode->GetChildFolderNode())
Чтобы не делать сокращений лучше в начале добавить child, чтобы было childFolderNode и childAssetNode + это сразу понятнее становится, что это конкретно

2020-11-12 16:29 UTC, nikchernyakov commented on DreamEngine.Assets/AssetTree.cpp
> +       for (auto* fdNode : folderNode->GetChildFolderNode())
Чтобы не делать сокращений лучше в начале добавить child, чтобы было childFolderNode и childAssetNode + это сразу понятнее становится, что это конкретно

2020-11-12 16:29 UTC, nikchernyakov commented on DreamEngine.Assets/AssetTree.cpp
> +       parentNode->removeChildFolderNode(folderNode);
Супер тупая оптимизационная придирка, но всё же
Лучше эту строчку сделать перед всеми циклами, чтобы пробег по массиву был меньше, пока туда не добавилось ещё нодов

2020-11-12 16:29 UTC, nikchernyakov commented on DreamEngine.Assets/AssetTree.cpp
> +    FolderNode* parenrNode = assetNode->GetParentNode();
ошибка в имени

2020-11-12 16:29 UTC, nikchernyakov commented on DreamEngine.Assets/AssetTree.cpp
> +    newParentNode->setChildFolderNode(folderNode);
У старого родителя нужно же удалить ссылку на ребёнка этого, вдруг мы просто переместили ноду, но родителя не удаляли?

2020-11-12 16:29 UTC, nikchernyakov commented on DreamEngine.Assets/AssetTree.cpp
> +    newParentNode->setChildAssetNode(assetNode);
У старого родителя нужно же удалить ссылку на ребёнка этого, вдруг мы просто переместили ноду, но родителя не удаляли?

2020-11-12 19:10 UTC, nikchernyakov requested changes

2020-11-12 19:10 UTC, nikchernyakov commented on DreamEngine.Assets/AssetNode.cpp
> +AssetNode::AssetNode()
Так а чё ты в самый верх не кинул конструктор?

2020-11-12 19:10 UTC, nikchernyakov commented on DreamEngine.Assets/AssetServices.cpp
> +    pathVar = pathVar + "/" +  node->GetName() + ".asset";
Сделай лучше для этого ещё метод CreateAssetPath, потому что тебе ещё не раз придётся такую строку писать

2020-11-12 19:10 UTC, nikchernyakov commented on DreamEngine.Assets/AssetServices.cpp
> +    std::filesystem::path pathVar(CreateFolderPath(node->GetParent()));
Здесь как раз тоже можно сделать сразу вызов CreateAssetPath
А так у тебя кажется даже ошибка кажется, потому что ты никак не указываешь имя и тип файла

2020-11-12 19:10 UTC, nikchernyakov commented on DreamEngine.Assets/AssetServices.cpp
> +       path = currentNode->GetName() + "/" + path;
Забыл смещать currentNode на родителя. Сейчас уйдёшь в бесконечный цикл

2020-11-12 19:10 UTC, nikchernyakov commented on DreamEngine.Assets/AssetTree.cpp
> +FolderNode* AssetTree::rootNode = new FolderNode("Content", nullptr);
Я уже который раз смотрю на это и меня коробит. Может инициализацию в header файле всё же сделаем? Первый раз вижу, чтобы переменные инициализировались в cpp файле

2020-11-12 19:10 UTC, nikchernyakov commented on DreamEngine.Assets/AssetTree.cpp
> +
Лишний отступ

2020-11-12 19:10 UTC, nikchernyakov commented on DreamEngine.Assets/AssetTree.cpp
> +    folderNode->GetParent()->removeChildFolderNode(folderNode);
Нет проверки, если parent - null

2020-11-12 19:10 UTC, nikchernyakov commented on DreamEngine.Assets/AssetTree.cpp
> +    assetNode->GetParent()->removeChildAssetNode(assetNode);
Нет проверки, если parent - null

2020-11-12 19:10 UTC, nikchernyakov commented on DreamEngine.Assets/FolderNode.h
> +    std::vector<FolderNode*> GetChildFolderNode();
Так и не поменял

2020-11-12 19:10 UTC, nikchernyakov commented on DreamEngine.Assets/FolderNode.h
> +
Лишний отступ

2020-11-12 20:34 UTC, Jass2100 commented on DreamEngine.Assets/FolderNode.h
> +    std::vector<FolderNode*> GetChildFolderNode();
у меня изменены они даже в комите странно что тут отображается старая

2020-11-12 20:37 UTC, Jass2100 commented on DreamEngine.Assets/AssetTree.cpp
> +FolderNode* AssetTree::rootNode = new FolderNode("Content", nullptr);
Ну это объявление статик переменной из анрила, привык так делать.

2020-11-14 18:19 UTC, nikchernyakov requested changes

2020-11-14 18:19 UTC, nikchernyakov commented on DreamEngine.Assets/AssetServices.cpp
> +        std::cout << "Error: " << e.what() << '\n';
Давай через логгер наш это сделаем + поменяй текст ошибки, чтобы было понятно, что ошибка в удалении ассета + сообщение в exception

2020-11-14 18:19 UTC, nikchernyakov commented on DreamEngine.Assets/AssetServices.cpp
> +    queueFolders.push_back(assetTree->GetRootNode());
Так ты же удалил уже рутовую ноду к этому моменту, её же сначала нужно создать

2020-11-14 18:19 UTC, nikchernyakov commented on DreamEngine.Assets/AssetServices.cpp
> +    std::vector<FolderNode*> queueFolders;
Поменяй на foldersQueue плиз. А то это звучит также странно как arrayFolders

2020-11-14 18:19 UTC, nikchernyakov commented on DreamEngine.Assets/AssetServices.cpp
> +                    assetTree->AddFolderNode(childFolderNode, currentFolderNode);
Так а выше ты в конструктор передавал родителя, он не делает тоже самое?

2020-11-14 18:19 UTC, nikchernyakov commented on DreamEngine.Assets/AssetServices.cpp
> +                    assetTree->AddAssetNode(childAssetNode, currentFolderNode);
Так а выше ты в конструктор передавал родителя, он не делает тоже самое?

2020-11-14 18:19 UTC, nikchernyakov commented on DreamEngine.Assets/AssetServices.cpp
>          std::cout << "Error: " << e.what() << '\n';
Давай через логгер наш это сделаем + поменяй текст ошибки, чтобы было понятно, что ошибка в удалении ассета + сообщение в exception

2020-11-14 18:19 UTC, nikchernyakov commented on DreamEngine.Assets/AssetServices.cpp
> +    std::filesystem::path pathVar(CreateFolderPath(folderNode->GetParent()));
А почему ты здесь получаешь родителя?

2020-11-14 18:19 UTC, nikchernyakov commented on DreamEngine.Assets/AssetServices.cpp
> +    std::filesystem::path pathVar(CreateFolderPath(folderNode->GetParent()));
Как ты удаляешь тогда ту конкретную папку?

2020-11-14 18:19 UTC, nikchernyakov commented on DreamEngine.Assets/AssetServices.cpp
> +    FolderNode* currentNode = assetNode->GetParent();
Переменные лучше объявлять в тех местах, когда начинаешь их использовать. Это упрощает их поиск и не миксует логику.

2020-11-14 18:19 UTC, nikchernyakov commented on DreamEngine.Assets/AssetServices.cpp
> +void AssetServices::ClearAssetTree()
Мне кажется, что этот метод должен быть внутри asset tree сделан

2020-11-14 18:19 UTC, nikchernyakov commented on DreamEngine.Assets/AssetServices.cpp
> +    assetTree->RemoveFolderNode(assetTree->GetRootNode(), true);
Либо здесь тебе нужно заново создавать Content ноду заново

2020-11-14 18:19 UTC, nikchernyakov commented on DreamEngine.Assets/AssetServices.cpp
>      try
Обработку ошибки нужно перенести на уровень там, где эта ошибка произойдёт. В данном случае, я так понимаю, исключение отслеживается в месте, где идёт чтение файла. Только там этот catch и нужно делать. Иначе один неправильно прочитанный файл у тебя ломает всё считывание файлов

2020-11-14 18:19 UTC, nikchernyakov commented on DreamEngine.Assets/AssetTree.h
> +    static AssetTree& GetInstance();
А почему не указатель возвращаешь кстати?

2020-11-14 18:19 UTC, nikchernyakov commented on DreamEngine.Assets/AssetTree.cpp
> +    }
В конце нужно удалить сам объект folderNode из памяти. Либо понять, где это правильнее делать

2020-11-14 18:19 UTC, nikchernyakov commented on DreamEngine.Assets/AssetTree.cpp
> +    parentNode->removeChildAssetNode(assetNode);
В конце нужно удалить сам объект assetNode из памяти. Либо понять, где это правильнее делать

2020-11-14 18:19 UTC, nikchernyakov commented on DreamEngine.Assets/AssetTree.cpp
> +    if (folderNode->GetParent() == nullptr) return;
Лучше сделать if как ты сделал это в MoveAssetNode, иначе у нас даже не будет лога месседжа, а ничего не произойдёт

2020-11-14 18:21 UTC, Jass2100 commented on DreamEngine.Assets/AssetServices.cpp
> +    queueFolders.push_back(assetTree->GetRootNode());
рутовая нода не удаляется она только чистится

2020-11-14 18:35 UTC, Jass2100 commented on DreamEngine.Assets/AssetServices.cpp
> +    std::filesystem::path pathVar(CreateFolderPath(folderNode->GetParent()));
осталось после изменения логики создания пути

2020-11-14 18:36 UTC, Jass2100 commented on DreamEngine.Assets/AssetServices.cpp
> +    assetTree->RemoveFolderNode(assetTree->GetRootNode(), true);
Зачем её создавать если она полностью чистая и я её не удаляю

2020-11-14 18:53 UTC, Jass2100 commented on DreamEngine.Assets/AssetTree.h
> +    static AssetTree& GetInstance();
Да привык когда синглтон возвращать ссылку, чтобы у неё всегда одно место в памяти было + невозможность nullptr

2020-11-14 19:07 UTC, Jass2100 commented on DreamEngine.Assets/AssetServices.cpp
>      try
Думаю что тут исключение вообще не нужно. Оно осталось после переделки логики когда мы могли к любой папке обратится а теперь только к контенту. И она всегда будет

2020-11-14 19:13 UTC, Jass2100 commented on DreamEngine.Assets/AssetTree.cpp
> +    if (folderNode->GetParent() == nullptr) return;
Ну тут проверка на рут ноду идёт. По факту могу лог вывести с варнингом, что нельзя таскать рут ноду

2020-11-14 19:46 UTC, nikchernyakov commented on DreamEngine.Assets/AssetTree.cpp
> +    if (folderNode->GetParent() == nullptr) return;
Да, добавь лог тогда

2020-11-14 19:47 UTC, nikchernyakov commented on DreamEngine.Assets/AssetTree.h
> +    static AssetTree& GetInstance();
¯\_(ツ)_/¯ Наверное, не особо ещё подружился с ссылками

2020-11-14 19:48 UTC, nikchernyakov commented on DreamEngine.Assets/AssetServices.cpp
>      try
Ну если исключений не выскочит, то ок, можешь удалить

2020-11-15 14:30 UTC, nikchernyakov requested changes

2020-11-15 14:30 UTC, nikchernyakov commented on DreamEngine.Assets/AssetServices.cpp
> +
Лишние отступы

2020-11-15 14:30 UTC, nikchernyakov commented on DreamEngine.Assets/AssetServices.cpp
>      // Exception for directories not found
Комментарий не удалил

2020-11-15 14:30 UTC, nikchernyakov commented on DreamEngine.Assets/AssetServices.cpp
> +        FolderNode* currentFolderNode = foldersQueue.at(0);
А это вынимает объект из очереди прям? Или только берёт?

2020-11-15 14:30 UTC, nikchernyakov commented on DreamEngine.Assets/AssetServices.cpp
> +   while(currentNode != nullptr )
Лишний пробел между nullptr и скобкой

2020-11-15 14:30 UTC, nikchernyakov commented on DreamEngine.Assets/AssetServices.cpp
> +   while(currentNode != nullptr )
И нету пробела после while

2020-11-15 14:30 UTC, nikchernyakov commented on DreamEngine.Assets/AssetServices.cpp
> +        for(std::filesystem::directory_iterator itr(directory_name); itr != endIntr; ++itr)
Пробел после for

2020-11-15 14:30 UTC, nikchernyakov commented on DreamEngine.Assets/AssetServices.cpp
> +            if(is_directory(itr->status()))
Пробел после if

2020-11-15 14:30 UTC, nikchernyakov commented on DreamEngine.Assets/AssetServices.cpp
> +    FolderNode* currentNode = assetNode->GetParent();
Вообще можно было бы не дублировать логику, а просто вызвать CreateFolderPath и прибавить к нему asset

2020-11-15 14:30 UTC, nikchernyakov commented on DreamEngine.Assets/AssetNode.cpp
> +    AssetTree::GetInstance().AddAssetNode(this, parentNode);
Сломается скорее всего. Ты вроде не можешь обращаться к объекту, пока ещё не закончился конструктор, а внутри AddAssetNode ты это будешь делать + зачем тебе вообще так сложно обращаться к этому и дублировать вставление родителя? Просто вызови у parent ноды метод на добавление ребёнка и добавь this

2020-11-15 14:30 UTC, nikchernyakov commented on DreamEngine.Assets/AssetTree.cpp
> +            delete folderNode;
Очень неочевидный и запрятанное удаление объекта имхо. Мы вчера с тобой обсуждали, но я только спустя время осознал, почему это так.

Вынеси удаление из глобального ифа, сделай отдельный иф с проверкой на то, что у folder нет родителя и удаляй. И оставь комментарий в коде плиз, что мы не удаляем root ноду

2020-11-15 14:30 UTC, nikchernyakov commented on DreamEngine.Assets/AssetTree.cpp
> +    if (assetNode->GetParent() == nullptr) return;
Здесь тоже нужно warning оставить, потому что такого кейса в идеальном случае не должно быть

2020-11-15 14:30 UTC, nikchernyakov commented on DreamEngine.Assets/AssetTree.cpp
> +        ErrorLogger::Log(Warning, "Cannot move the Content folder");
Лучше переименнуй это в root folder

2020-11-15 14:30 UTC, nikchernyakov commented on DreamEngine.Assets/FolderNode.cpp
> +    parentNode->addChildFolderNode(this);
Воо, тут ты правильно делаешь то, как должен сделать это в AssetNode

2020-11-15 14:41 UTC, Jass2100 commented on DreamEngine.Assets/AssetNode.cpp
> +    AssetTree::GetInstance().AddAssetNode(this, parentNode);
потому что folderNode и AssetNode не являются дружественными классами

2020-11-15 14:45 UTC, nikchernyakov commented on DreamEngine.Assets/AssetNode.cpp
> +    AssetTree::GetInstance().AddAssetNode(this, parentNode);
Хм... Ну возможно имеет смысл их обоих сделать дружественными друг другу

2020-11-15 14:47 UTC, Jass2100 commented on DreamEngine.Assets/AssetNode.cpp
> +    AssetTree::GetInstance().AddAssetNode(this, parentNode);
Ну если мы не хотим придерживаться плана что только AssetTree дружественный то да могу сделать

2020-11-15 14:51 UTC, nikchernyakov commented on DreamEngine.Assets/AssetNode.cpp
> +    AssetTree::GetInstance().AddAssetNode(this, parentNode);
Мы же делали AssetTree дружественным, чтобы извне к этому никто не имел доступа. А AssetNode и FolderNode связанные сущности, которые в целом могут друг к другу иметь доступ. Иначе довольно извращённая работа через AssetTree получается. Либо сделай только дружественным метод AddAssetNode в FolderNode классе для AssetNode

2020-11-15 14:52 UTC, Jass2100 commented on DreamEngine.Assets/AssetNode.cpp
> +    AssetTree::GetInstance().AddAssetNode(this, parentNode);
Не уж лучше тогда весь класс сделать дружественным

2020-11-15 15:03 UTC, nikchernyakov requested changes

2020-11-15 15:03 UTC, nikchernyakov commented on DreamEngine.Assets/AssetServices.cpp
> +    FolderNode* currentNode = assetNode->GetParent();
Это будешь менять?

2020-11-15 15:06 UTC, nikchernyakov approved these changes

2020-11-15 17:07 UTC, MMTsallagova approved these changes

2020-11-15 17:13 UTC, merged