Refactor window initialization
itmo-engine-team/dream-engine pull request #4
Opened 2020-09-21 18:31 UTC by MMTsallagova

Refactor window initialization:
- Create new class Window and add new function for window Initialization
- Add variables to constructor Game class constructor

2020-09-21 18:38 UTC, nikchernyakov approved these changes

2020-09-21 18:39 UTC, nikchernyakov requested changes

2020-09-21 18:39 UTC, nikchernyakov commented on Engine/Game.h
> +	Window* window;
Эту переменную тоже нужно перенести в protected блок

2020-09-22 12:58 UTC, nikchernyakov approved these changes

2020-09-22 13:25 UTC, Jass2100 approved these changes

2020-09-22 13:55 UTC, merged