Unit test for folders and asset. Fixed asset tree
itmo-engine-team/dream-engine pull request #47
Opened 2020-11-28 17:12 UTC by Jass2100

2020-11-29 08:34 UTC, MMTsallagova approved these changes

2020-11-29 12:06 UTC, nikchernyakov requested changes

2020-11-29 12:06 UTC, nikchernyakov commented on DreamEngine.Assets/AssetServices.cpp
>      const std::string extension = ".asset";
Вот это нужно в глобальную константу вынести у AssetService и везде использовать, где нужно

2020-11-29 12:06 UTC, nikchernyakov commented on DreamEngine.Assets/AssetServices.cpp
> +                FolderModificationResult childFolderStruct = assetTree->CreateFolderNode(
Какое-то странное название переменной

2020-11-29 12:06 UTC, nikchernyakov commented on DreamEngine.Assets/AssetServices.cpp
> +            {
Здесь видимо пробелы лишние

2020-11-29 12:06 UTC, nikchernyakov commented on DreamEngine.Assets/AssetServices.cpp
> +           std::string error = std::string("MoveFileEx failed with error %d\n", GetLastError());
Так тут тоже нужно возвращать ошибку в виде FolderModificationResult

2020-11-29 12:06 UTC, nikchernyakov commented on DreamEngine.Assets/AssetServices.cpp
> +
Лишняя строчка

2020-11-29 12:06 UTC, nikchernyakov commented on DreamEngine.Assets/AssetServices.cpp
>      const std::string extension = ".asset";
Это нужно добавить в глобальную переменную у AssetServices и везде использовать

2020-11-29 12:06 UTC, nikchernyakov commented on DreamEngine.Assets/AssetServices.cpp
> +                FolderModificationResult childFolderStruct = assetTree->CreateFolderNode(
Странное название переменной, хотя я сам сходу не могу какое-то нормальное название придумать, не хочется слишком длинное делать
childFolderModificationResult наверное слишком длинное
Ну может хотя бы childFolderResult и так понятно, что modification

2020-11-29 12:06 UTC, nikchernyakov commented on DreamEngine.Assets/AssetServices.cpp
> +           std::string error = std::string("MoveFileEx failed with error %d\n", GetLastError());
Здесь тоже ошибку нужно оборачивать в ModificationResult

2020-11-29 12:06 UTC, nikchernyakov commented on DreamEngine.Assets/AssetServices.cpp
> +        std::string error = "MoveFileEx failed with error: " + GetLastError();
Здесь тоже ModificationResult нужно возвращать

2020-11-29 12:06 UTC, nikchernyakov commented on DreamEngine.Assets/AssetServices.cpp
> +        std::string error = std::string("MoveFileEx failed with error %d\n", GetLastError());
Здесь тоже ModificationResult нужно возвращать

2020-11-29 12:06 UTC, nikchernyakov commented on DreamEngine.Assets/AssetTree.cpp
> +   FolderModificationResult folderStruct;
Вместо Struct давай лучше Result использовать, мне кажется, так нагляднее

2020-11-29 12:06 UTC, nikchernyakov commented on DreamEngine.Assets/AssetTree.h
> +    bool resault;
Очепятка в имени переменной, но лучше вообще переименовать это в isSuccess

2020-11-29 12:06 UTC, nikchernyakov commented on DreamEngine.Assets/AssetTree.h
> +    bool resault;
Очепятка в имени переменной, но лучше вообще переименовать это в isSuccess

2020-11-29 12:06 UTC, nikchernyakov commented on UnitTest/AssetTest.cpp
> +    printf(assetStruct.error.c_str());
error нужно же выводить только если result != true

2020-11-29 12:06 UTC, nikchernyakov commented on UnitTest/AssetTest.cpp
> +    if(folderStruct.resault)
Такое написание ифа нужно запрещать на законодательном уровне
Если в else пишешь скобочки, то в if блоке тоже их нужно делать, иначе это очень путано выглядит

2020-11-29 12:06 UTC, nikchernyakov commented on UnitTest/AssetTest.cpp
> +    if(folderStruct.resault)
+ между if и ( пробел нужен

2020-11-30 12:09 UTC, Jass2100 commented on DreamEngine.Assets/AssetServices.cpp
> +            {
Какие пробелы?

2020-11-30 13:26 UTC, nikchernyakov requested changes

2020-11-30 13:26 UTC, nikchernyakov commented on DreamEngine.Assets/AssetServices.h
> +const std::string EXTENSION = ".asset";
А зачем так высоко?
Лучше запихнуть внутрь неймспейса, чтобы это относилось к AssetService
И переименуй плиз в ASSET_FILE_EXTENSION

2020-11-30 13:26 UTC, nikchernyakov commented on DreamEngine.Assets/AssetTree.cpp
> +    AssetModificationResult assetStruct;
assetResult

2020-11-30 13:56 UTC, Jass2100 commented on DreamEngine.Assets/AssetServices.h
> +const std::string EXTENSION = ".asset";
Ну когда читаю сделать глобальной обычно понимаю как вынести за класс или нэймспэйс

2020-11-30 14:11 UTC, nikchernyakov commented on DreamEngine.Assets/AssetServices.h
> +const std::string EXTENSION = ".asset";
Значит я не точно сформулировал)
Я имел ввиду вынести за пределы функции, но оставил в области AssetService

2020-11-30 18:47 UTC, nikchernyakov approved these changes

2020-11-30 18:55 UTC, merged