Asset browser
itmo-engine-team/dream-engine pull request #50
Opened 2020-12-01 17:48 UTC by MMTsallagova

2020-12-01 18:49 UTC, nikchernyakov requested changes

2020-12-01 18:49 UTC, nikchernyakov commented on DreamEngine.Editor/EditorWindowAssetBrowser.cpp
> +    //add folder icon
Комментарий начинается с пробела и с большой буквы

2020-12-01 18:49 UTC, nikchernyakov commented on DreamEngine.Editor/EditorWindowAssetBrowser.cpp
> +    //begin tree
Комментарий начинается с пробела и с большой буквы

2020-12-01 18:49 UTC, nikchernyakov commented on DreamEngine.Editor/EditorWindowAssetBrowser.cpp
> +    int folders_count = parentNode->GetChildFolderList().size();
Имя переменной не по код стайлу

2020-12-01 18:49 UTC, nikchernyakov commented on DreamEngine.Editor/EditorWindowAssetBrowser.cpp
> +    int assets_count = parentNode->GetChildAssetList().size();
Имя переменной не по код стайлу

2020-12-01 18:49 UTC, nikchernyakov commented on DreamEngine.Editor/EditorWindowAssetBrowser.cpp
> +        if (ImGui::ImageButton(iconFolder->GetShaderResourceView(), buttonSize)) //need to fix
После ифа никогда не ставь комментарии, они очень легко теряются
Лучше ставь выше ифа + пометку TODO ставь, чтобы легче было найти
+ можно расписать хотя бы, что пофиксить вкратце, а то потом забудешь

2020-12-01 18:49 UTC, nikchernyakov commented on DreamEngine.Editor/EditorWindowAssetBrowser.h
> +    void popupContextMenu();
У тебя методы то с create начинаются, то просто с названия элемента. Давай это всё одним названием?
И лучше, чтобы не create впереди был, а draw например. Слово Create для другого предполагается

2020-12-01 18:49 UTC, nikchernyakov commented on DreamEngine.Editor/EditorWindowAssetBrowser.h
> +    const char* fileNames[];
У тебя этот массив вообще используется? Я так понимаю, это для фильтра массив, но в месте, где фильтр создаётся, там переменная и так инициализируется

2020-12-01 18:49 UTC, nikchernyakov commented on DreamEngine.Editor/EditorWindowAssetBrowser.h
> +    FolderNode* rootNode;
Переменная используется вообще?

2020-12-01 18:49 UTC, nikchernyakov commented on DreamEngine.Editor/EditorWindowAssetBrowser.cpp
> +    for (int i = 0; i < parentNode->GetChildAssetList().size(); i++)
Для таких циклов используй лучше foreach, они намного читабельнее и сокращают количество кода и лишних данных

2020-12-01 18:49 UTC, nikchernyakov commented on DreamEngine.Editor/EditorWindowAssetBrowser.h
> +    void addTreeFolders(FolderNode* parentNode);
Непонятное название функций этих двух
Лучше что-нибудь типа drawChildrenAssets и drawChildrenFolders, ты же по факту рисуешь детей определённой папки

2020-12-01 18:49 UTC, nikchernyakov commented on DreamEngine.Editor/EditorWindowAssetBrowser.cpp
> +    for (int i = 0; i < parentNode->GetChildFolderList().size(); i++)
Для таких циклов используй лучше foreach, они намного читабельнее и сокращают количество кода и лишних данных

2020-12-01 18:49 UTC, nikchernyakov commented on DreamEngine.Editor/EditorWindowAssetBrowser.cpp
> +        if (ImGui::Selectable("New")) {}
Это вообще нужно циклом обрабатывать и тоже как-то отдельным списком хранить, потому что ты несколько раз эти названия берёшь

2020-12-01 18:49 UTC, nikchernyakov commented on DreamEngine.Editor/EditorWindowAssetBrowser.cpp
> +        if (ImGui::Selectable("New")) {}
Но я думаю, что там легче отдельный класс реализовать для этих элементов. Можем это оставить как задачу на потом, когда ты за реализацию логики кнопок сядешь

2020-12-01 18:49 UTC, nikchernyakov commented on DreamEngine.Editor/EditorWindowAssetBrowser.cpp
> +        if (i + 1 < assets_count && nextButton < windowVisible)
nextButton < windowVisible 
Не воспринимаемо имхо, как будто две несравнимые понятия сравниваешь. 
У тебя же это всё PositionX, добавь этому хотя бы такой суффикс

2020-12-01 18:49 UTC, nikchernyakov commented on DreamEngine.Editor/EditorWindowAssetBrowser.cpp
> +        float lastButton = ImGui::GetItemRectMax().x;
У тебя вообще дублируется логика с тем, что на 108 строке. Может лучше вынести в отдельную функцию?

2020-12-01 18:49 UTC, nikchernyakov commented on DreamEngine.Editor/EditorWindowAssetBrowser.cpp
> +    if (ImGui::TreeNode(assetTree->GetRootNode()->GetName().c_str()))
Насколько я понял, у тебя логика здесь совпадает с тем, что в addTreeFolders методе
Только там ты по детям пробегаешься сразу
Сделай вместо этого метод drawFolder, который рисует папку, а потом бежит по детям и рекурсией вызывает этот же метод для них

2020-12-01 18:49 UTC, nikchernyakov commented on DreamEngine.Editor/EditorWindowAssetBrowser.cpp
> +    ImGui::Image(iconFilter->GetShaderResourceView(), ImVec2(20, 20));
Эти две строки напрашиваются на метод отдельный, ибо ты везде это используешь одинаково, только иконка меняется

2020-12-01 18:51 UTC, MMTsallagova commented on DreamEngine.Editor/EditorWindowAssetBrowser.cpp
> +        if (i + 1 < assets_count && nextButton < windowVisible)
Это я даже не трогаю. Это из библиотеки, чтобы выровнять правильно по количеству кнопок всё

2020-12-01 18:56 UTC, MMTsallagova commented on DreamEngine.Editor/EditorWindowAssetBrowser.cpp
> +        float lastButton = ImGui::GetItemRectMax().x;
Разные типы. Для GetChildAssetList - это AssetNode*, для GetChildFolderList - FolderNode*. Я пробовала уже, не выходит для них одну функцию скормить

2020-12-01 18:58 UTC, MMTsallagova commented on DreamEngine.Editor/EditorWindowAssetBrowser.cpp
> +    if (ImGui::TreeNode(assetTree->GetRootNode()->GetName().c_str()))
Нет, мы отсюда стартуем. Это как раз для того, чтобы отрисовать первую папку и передать корень. Как только он передается - идет рекурсия

2020-12-01 18:59 UTC, MMTsallagova commented on DreamEngine.Editor/EditorWindowAssetBrowser.cpp
> +    ImGui::Image(iconFilter->GetShaderResourceView(), ImVec2(20, 20));
Я решила, что делать один метод для 2х строк только чтобы вместо 2х была 1 строка - такое себе

2020-12-01 19:02 UTC, MMTsallagova commented on DreamEngine.Editor/EditorWindowAssetBrowser.cpp
> +        if (ImGui::Selectable("New")) {}
Может быть, но пока мне не кажется это хорошей идеей. Функционал будет разный для каждой кнопки, включая повторы с menuBar (если я правильно поняла)

2020-12-01 19:03 UTC, MMTsallagova commented on DreamEngine.Editor/EditorWindowAssetBrowser.cpp
> +        if (ImGui::ImageButton(iconFolder->GetShaderResourceView(), buttonSize)) //need to fix
Папки с layout под фильтром не обновляются при нажатии на них в этой области

2020-12-01 19:10 UTC, MMTsallagova commented on DreamEngine.Editor/EditorWindowAssetBrowser.h
> +    const char* fileNames[];
Пусть пока будет, она понадобится для заполнения массива именами файлов для поиска

2020-12-01 19:40 UTC, nikchernyakov requested changes

2020-12-01 19:40 UTC, nikchernyakov commented on DreamEngine.Editor/EditorWindowAssetBrowser.cpp
> +    if (ImGui::TreeNode(assetTree->GetRootNode()->GetName().c_str()))
Я понимаю, но метод можно немного поменять так, чтобы это всё можно было через один вызов функции сделать
То есть алгоритм этой функции 
1. Рисуешь папку 
2. Бежишь рекурсивно по детям
3. TreePop

И просто передаёшь туда на старте рут ноду

2020-12-01 19:40 UTC, nikchernyakov commented on DreamEngine.Editor/EditorWindowAssetBrowser.cpp
> +    for (int i = 0; i < parentNode->GetChildAssetList().size(); i++)
?

2020-12-01 19:40 UTC, nikchernyakov commented on DreamEngine.Editor/EditorWindowAssetBrowser.cpp
> +    for (int i = 0; i < parentNode->GetChildFolderList().size(); i++)
?

2020-12-01 20:32 UTC, nikchernyakov requested changes

2020-12-01 20:32 UTC, nikchernyakov commented on DreamEngine.Editor/EditorWindowAssetBrowser.cpp
> +    for (auto i : parentNode->GetChildAssetList())
Имя i используется для счётчика, Лучше используй нормальное имя объекта
Например assetNode

2020-12-01 20:32 UTC, nikchernyakov commented on DreamEngine.Editor/EditorWindowAssetBrowser.cpp
> +    for (auto i : parentNode->GetChildFolderList())
Имя i используется для счётчика, Лучше используй нормальное имя объекта
Например childFolderNode

2020-12-02 09:49 UTC, nikchernyakov approved these changes

2020-12-02 11:11 UTC, Jass2100 approved these changes

2020-12-02 11:24 UTC, merged