Rework modification result structure
itmo-engine-team/dream-engine pull request #51
Opened 2020-12-01 19:04 UTC by nikchernyakov

2020-12-01 19:59 UTC, Jass2100 requested changes

2020-12-01 19:59 UTC, Jass2100 commented on DreamEngine.Assets/TreeModificationResult.h
> +    TreeModificationResult(const std::string error) : isSuccess(false), node(nullptr), error(error) {}
Мне кажется это слишком неявные конструкторы, я сначала потерялся пытаясь понять как ты получаешь эти значения, думаю лучше сделать конструктор с дефолтными значениями. по факту тут делается что якобы если мы передали какую-то ошибку то 100 процентов у нас nullptr, хотя сам в одном месте передаёшь всю структуру так как есть исключения, что есть ошибка и есть ссылка на ноду.

2020-12-01 20:01 UTC, Jass2100 requested changes

2020-12-01 20:01 UTC, Jass2100 commented on DreamEngine.Assets/AssetServices.cpp
> +                "MoveFileEx failed with error %d\n", GetLastError())
кажется лишний таб или на 172 наоборот его не хватает.

2020-12-01 20:01 UTC, Jass2100 commented on DreamEngine.Assets/AssetServices.cpp
> +                    "MoveFileEx failed with error %d\n", GetLastError())
лишний таб

2020-12-01 20:35 UTC, nikchernyakov commented on DreamEngine.Assets/TreeModificationResult.h
> +    TreeModificationResult(const std::string error) : isSuccess(false), node(nullptr), error(error) {}
Я сделал так, чтобы сократить количество кода, которые нужно делать для создания структурки
Если мы передаём ноду, то явно результат правильный, зачем всё остальное передавать. Тоже самое, если ошибка.
Но если было непонятно, то ладно, добавлю ещё первым аргументом isSuccess

2020-12-01 20:39 UTC, Jass2100 commented on DreamEngine.Assets/TreeModificationResult.h
> +    TreeModificationResult(const std::string error) : isSuccess(false), node(nullptr), error(error) {}
Не всегда если передаем ноду это true например в строчке 114 AssetService, ты передаешь всю структуру так как там исключение

2020-12-01 20:49 UTC, nikchernyakov commented on DreamEngine.Assets/TreeModificationResult.h
> +    TreeModificationResult(const std::string error) : isSuccess(false), node(nullptr), error(error) {}
В итоге, оставил только один конструктор со всеми аргументами, двум последним выставил дефолтные значения

2020-12-01 20:53 UTC, Jass2100 commented on DreamEngine.Assets/TreeModificationResult.h
> +    TreeModificationResult(bool isSuccess, T* node = nullptr, std::string error = "")
Не знаю может и зря душить начал, но по мне так выглядит более понятно и у всех нас будет подсказка от визуалки, что у переменных если что есть дефолт

2020-12-01 20:53 UTC, Jass2100 approved these changes

2020-12-02 09:44 UTC, MMTsallagova approved these changes

2020-12-02 09:49 UTC, merged