Serialize/Deserialize actor
itmo-engine-team/dream-engine pull request #53
Opened 2020-12-03 19:30 UTC by Jass2100

2020-12-03 20:29 UTC, nikchernyakov requested changes

2020-12-03 20:29 UTC, nikchernyakov commented on DreamEngine.Assets/AssetService.cpp
> +#include"Serializer.h"
Пробела не хватает

2020-12-03 20:29 UTC, nikchernyakov commented on DreamEngine.Assets/AssetService.cpp
> +void AssetService::SerializeActor(Serializer* actor, std::filesystem::path pathToConfig)
Почему вообще эктор? Эктор вообще никак не связан со всем этим. Надо либо file это назвать, либо serializableObject, либо просто serializable.

Тоже самое со вторым аргументом. Если это общий метод, то это не только для конфига. Значит надо назвать что-нибудь типа pathToFile

2020-12-03 20:29 UTC, nikchernyakov commented on DreamEngine.Assets/AssetService.cpp
> +Serializer* AssetService::createSerializerActor(Serializer* actor, std::filesystem::path pathToConfig)
Тоже самое по неймингу
Название фунции также сменить

2020-12-03 20:29 UTC, nikchernyakov commented on DreamEngine.Assets/AssetService.h
> +    static T* DeserializeActor(std::filesystem::path pathToConfig)
Тоже самое по неймингу

2020-12-03 20:29 UTC, nikchernyakov commented on DreamEngine.Assets/Serializer.h
> +class Serializer
Имхо Serializer - это класс, который что-то сериализует, как сторонний инструмент
У нас же класс, который сам сериализуется. Лучше как в джавке какой-нибудь это назвать Serializable

2020-12-03 20:29 UTC, nikchernyakov commented on DreamEngine.Assets/Serializer.h
> +public:
Мне кажется, это можно сделать протектед и сделать AssetService другом. Только там эти функции вызываются

2020-12-03 20:29 UTC, nikchernyakov commented on DreamEngine.Assets/EngineConfigInfo.h
> +    bool isGameMode = false;
Приватной сделать и геттер к ней

2020-12-03 20:29 UTC, nikchernyakov commented on DreamEngine.Assets/EngineConfigInfo.cpp
> +    std::ifstream i(pathToConfig);
Это проблема, зачем нам каждый раз для любого класса открывать файл и оттуда всё читать
Это должно быть превращено в json ещё в AssetService

2020-12-03 20:29 UTC, nikchernyakov commented on DreamEngine.Assets/EngineConfigInfo.cpp
> +    std::ifstream i(pathToConfig);
Также нету вызова родителя

2020-12-03 20:29 UTC, nikchernyakov commented on DreamEngine.Assets/AssetService.cpp
> +        SerializeActor(actor, pathToConfig);
В плане, что это проблема с архитектурой этого всего

2020-12-03 20:29 UTC, nikchernyakov commented on DreamEngine.Assets/AssetService.h
> +        actor = static_cast<T*>(createSerializerActor(actor, pathToConfig));
Зачем тебе вообще возвращать этот же объект, если у тебя всё равно указатель

2020-12-03 20:29 UTC, nikchernyakov commented on DreamEngine.Assets/AssetService.h
> +        actor = static_cast<T*>(createSerializerActor(actor, pathToConfig));
Тебе не нужно короче это к actor присваивать

2020-12-03 20:29 UTC, nikchernyakov commented on DreamEngine.Assets/AssetService.h
> +    static T* DeserializeActor(std::filesystem::path pathToConfig)
Вообще лучше также назвать как в Serializer назвать эти методы From и To
Никогда не любил названия типа Serialize и Deserialize, пока не посмотришь точно, не будешь уверен, какой у функции возвращаемый тип

2020-12-03 20:29 UTC, nikchernyakov commented on DreamEngine.Assets/Serializer.h
> +    virtual Serializer* FromJson(std::filesystem::path pathToConfig) = 0;
FromJson должен принимать на вход json, возвращать он ничего не должен

2020-12-03 20:29 UTC, nikchernyakov commented on DreamEngine.Assets/Serializer.h
> +    virtual json ToJson() = 0;
ToJson можно реализовать прям тут, чтобы создать json объект внутри и передать дальше на наследников

2020-12-04 18:17 UTC, nikchernyakov approved these changes

2020-12-05 12:05 UTC, MMTsallagova approved these changes

2020-12-05 12:23 UTC, merged