New functions for asset service
itmo-engine-team/dream-engine pull request #58
Opened 2020-12-08 20:07 UTC by Jass2100

Save, rename, duplicate

2020-12-08 20:28 UTC, nikchernyakov requested changes

2020-12-08 20:28 UTC, nikchernyakov commented on DreamEngine.Assets/AssetService.cpp
> +        return { false, nullptr, "File already exist"};
Лучше ноду, которая к тебе пришла возвращать, я думаю

2020-12-08 20:28 UTC, nikchernyakov commented on DreamEngine.Assets/AssetService.cpp
> +        return { false, nullptr, "File already exist"};
В смысле не nullptr, а node делать

2020-12-08 20:28 UTC, nikchernyakov commented on DreamEngine.Assets/AssetService.cpp
> +    return  { true };
Здесь уж точно надо возвращать node. Ну и вообще если есть что вернуть, то лучше вернуть, мало ли это пригодится потом

2020-12-08 20:28 UTC, nikchernyakov commented on DreamEngine.Assets/AssetService.cpp
> +        return { true };
Ноду вернуть

2020-12-08 20:28 UTC, nikchernyakov commented on DreamEngine.Assets/AssetService.cpp
> +        return { false, nullptr, error };
Ноду вернуть

2020-12-08 20:28 UTC, nikchernyakov commented on DreamEngine.Assets/AssetService.h
> +    static AssetModificationResult DuplicateAsset(AssetNode* assetNode, std::string& newNodeName);
Давай всё-таки тебе будут передавать новое имя, которое у дубликата будет и логику с созданием нового имени перенесём выше. Ибо может быть мы добавим опцию, чтобы можно было сразу переименовать дубликат при создании

2020-12-09 16:31 UTC, Jass2100 commented on DreamEngine.Assets/AssetService.h
> +    static AssetModificationResult DuplicateAsset(AssetNode* assetNode, std::string& newNodeName);
а зачем мне имя передавать? В том же анриле примерно так дубликаты и генерируются, и потом дают уже переназвать

2020-12-09 16:41 UTC, nikchernyakov commented on DreamEngine.Assets/AssetService.h
> +    static AssetModificationResult DuplicateAsset(AssetNode* assetNode, std::string& newNodeName);
Я же написал ответ на этот вопрос. Логику как мы будем генерить имя  можно делать разную в разных обстоятельствах. Например для работы с ассетами лучше сразу предлагать менять имя, а уже потом создавать файл. А на какой-нибудь сцене легче генерировать сразу дубликат со сгенерированым именем.
Короче это не дело AssetService какое имя будет иметь новый ассет

2020-12-09 17:18 UTC, nikchernyakov approved these changes

2020-12-09 17:20 UTC, MMTsallagova approved these changes

2020-12-09 17:21 UTC, merged