DirectX-refactoring
itmo-engine-team/dream-engine pull request #6
Opened 2020-09-24 15:59 UTC by MMTsallagova

DirectX Initialization refactoring:
- Create new Graphics class and add new function for DirectX Initialization

2020-09-24 16:36 UTC, nikchernyakov approved these changes

2020-09-25 08:58 UTC, nikchernyakov requested changes

2020-09-25 08:58 UTC, nikchernyakov commented on Engine/Game.cpp
> +	graphics = new Graphics(this);
Почему создание объекта и его инициализация в разных местах кода?
Сделай, чтобы они вместе были, а от остального кода пустой строкой отдели

2020-09-25 08:58 UTC, nikchernyakov commented on Engine/Game.h
> +	ID3DUserDefinedAnnotation* annotation;
А с этим у тебя в итоге не получилось перенести?

2020-09-25 08:58 UTC, nikchernyakov commented on Engine/Game.h
> +	Graphics* graphics;
Верни это в protected блок, а для доступа сделай метод const GetGraphics()

2020-09-25 08:58 UTC, nikchernyakov commented on Engine/Graphics.cpp
> +	D3D11_TEXTURE2D_DESC descDepth;           // ��������� � �����������
Переведи плиз комменты на английский, а то они не отображаются на гите, да и по код стайлу неправильно

2020-09-25 08:58 UTC, nikchernyakov commented on Engine/Graphics.h
> +	ID3D11Device* device;
У тебя тут отступ какой-то лишний по сравнению с конструктором, где неправильно?

2020-09-25 08:58 UTC, nikchernyakov commented on Engine/Graphics.h
> +	ID3D11Texture2D* depthStencil = NULL;             // �������� ������ ������
Переведи плиз комменты на английский, а то они не отображаются на гите, да и по код стайлу неправильно

2020-09-25 08:58 UTC, nikchernyakov commented on Engine/MeshObject.cpp
> +	hr = game->graphics->device->CreateBuffer(
Чтобы не громоздить эту кучу соплей из обращений, можно в начале в конструкторе сохранить в переменную graphics. а потом к ней внутри обращаться

2020-09-25 08:58 UTC, nikchernyakov commented on Engine/Texture.cpp
>  	// �������� �������� �� �����
Переведи плиз комменты на английский, а то они не отображаются на гите, да и по код стайлу неправильно

2020-09-25 20:20 UTC, nikchernyakov requested changes
Сорян))

2020-09-25 20:20 UTC, nikchernyakov commented on Engine/Graphics.cpp
> +    return false;
Только сейчас заметил, а зачем здесь false возвращается?
Давай тогда уже true возвращать хотя бы, чтобы потом false возвращать в случае ошибки

2020-09-25 20:20 UTC, nikchernyakov commented on Engine/Graphics.cpp
> +
Раз всё равно менять этот файл, почини количество пустых строк
Чтобы не было больше одной пустой строки разрыва)

2020-09-25 20:20 UTC, nikchernyakov commented on Engine/Graphics.cpp
> +	/*Using the filled-in description structure and texture, create depth buffer object*/
Для комментариев в одну строку лучше использовать // и делай пробел между этими символами и текстом

2020-09-25 20:20 UTC, nikchernyakov commented on Engine/MeshObject.cpp
> +    graphics->GetContext()->IASetIndexBuffer(pIndexBuffer.Get(), DXGI_FORMAT_R32_UINT, 0u);
Тут отступ сломался

2020-09-25 20:20 UTC, nikchernyakov commented on Engine/Texture.cpp
> +	/*Loading a texture from file*/
Тут тоже замечание по поводу комментария

2020-09-26 07:51 UTC, nikchernyakov approved these changes

2020-09-26 10:13 UTC, Jass2100 approved these changes

2020-09-26 10:40 UTC, merged