Asset browser window
itmo-engine-team/dream-engine pull request #64
Opened 2020-12-15 19:01 UTC by MMTsallagova

Add Popup window for new assets

2020-12-15 19:50 UTC, nikchernyakov requested changes

2020-12-15 19:50 UTC, nikchernyakov commented on DreamEngine.Editor/EditorPopupModalNew.h
> +class EditorPopupModalNew : public EditorPopupModal
Нужно дать более точное имя
Суффикс New слишком мало инфы даёт. Ты же потом ещё для создания папки будешь делать Popup, как ты его назовёшь? Или ещё какую-нибудь новую штуку нужно будет создать. Давай NewAsset суффикс сделаем.

2020-12-15 19:50 UTC, nikchernyakov commented on DreamEngine.Editor/EditorPopupModalNew.h
> +    std::string assetNamePublic;
Зачем публичные переменные?

2020-12-15 19:50 UTC, nikchernyakov commented on DreamEngine.Editor/EditorPopupModalNew.h
> +    AssetInfoFactory* assetFactory;
AssetInfoFactory это статический класс, тебе не нужна переменная для него

2020-12-15 19:50 UTC, nikchernyakov commented on DreamEngine.Editor/EditorPopupModalNew.cpp
> +    int sizeStr = assetFactory->MAP_ASSET_TYPE_TO_STRING.size();
К assetInfoFactor нужно обращаться так
AssetInfoFactory::

2020-12-15 19:50 UTC, nikchernyakov commented on DreamEngine.Editor/EditorPopupModalNew.cpp
> +    for (auto iterator = assetFactory->MAP_ASSET_TYPE_TO_STRING.begin(); iterator != assetFactory->MAP_ASSET_TYPE_TO_STRING.end(); ++iterator)
Мне не нравится, что ты каждый кадр делаешь такие манипуляции со строками и мапами. Эти же строки всегда одни, давай эту инициализацию в конструктор перенесём?

2020-12-15 19:50 UTC, nikchernyakov commented on DreamEngine.Editor/EditorPopupModalNew.cpp
> +    for (auto iterator = assetFactory->MAP_ASSET_TYPE_TO_STRING.begin(); iterator != assetFactory->MAP_ASSET_TYPE_TO_STRING.end(); ++iterator)
Если я не ошибаюсь в плюсах такое тоже есть, можно в цикле несколько операций делать через запятую. То есть от глобального i можно избавиться так по идее:
for (int i = 0, auto iterator = assetFactory->MAP_ASSET_TYPE_TO_STRING.begin(); iterator != assetFactory->MAP_ASSET_TYPE_TO_STRING.end(); ++iterator, ++i)

2020-12-15 19:50 UTC, nikchernyakov commented on DreamEngine.Editor/EditorWindowAssetBrowser.cpp
> +       // ImGui::TreePop();
Это прозапас комментарий?

2020-12-15 19:50 UTC, nikchernyakov commented on DreamEngine.Editor/EditorWindowAssetBrowser.cpp
> +        if (newAssetPopupModal->assetNamePublic != "")
Вообще если передана пустая строка, это ошибка
Причём которую нужно обрабатывать на стороне popup 
Пока давай это опустим, когда продолжишь работу дальше, я добавлю дополнительную возможность для этого

2020-12-15 19:50 UTC, nikchernyakov commented on DreamEngine.Editor/EditorWindowAssetBrowser.cpp
> +void EditorWindowAssetBrowser::drawDeletePopup()
Ну и копипаст.... Надо подумать будет, как такого избежать. По идее, в отдельный метод это можно вынести

2020-12-15 19:50 UTC, nikchernyakov commented on DreamEngine.Editor/EditorWindowAssetBrowser.h
> +    EditorPopupModalText* testPopupModalText;
Тестовый popup можно удалить, я его добавлял только для демонстрации тебе

2020-12-15 19:50 UTC, nikchernyakov commented on DreamEngine.Editor/EditorWindowAssetBrowser.h
> +    void drawNewPopup();
Отдели лучше отступом от остальных методов

2020-12-15 20:03 UTC, nikchernyakov commented on DreamEngine.Editor/EditorPopupModalNew.h
> +    std::string assetNamePublic;
Увидел зачем, но в любом случае это надо либо обернуть в Get функцию, либо писать с большой буквы

2020-12-15 20:04 UTC, nikchernyakov commented on DreamEngine.Editor/EditorWindowAssetBrowser.cpp
> +        if (newAssetPopupModal->assetNamePublic != "")
Собственно, я закоммитил это
Теперь можешь наследовать метод onFinish и проверять, что имя не пусто, иначе возвращать false и окно не будет закрыто. Можно ещё ошибочки писать

2020-12-15 20:06 UTC, nikchernyakov commented on DreamEngine.Editor/EditorWindowAssetBrowser.cpp
> +        if (newAssetPopupModal->assetNamePublic != "")
Ещё у строки есть метод IsEmpty лучше её использовать

2020-12-15 20:13 UTC, nikchernyakov commented on DreamEngine.Editor/EditorWindowAssetBrowser.cpp
> +void EditorWindowAssetBrowser::drawDeletePopup()
Ну сократил 5 строк до 2.... Всё равно не очень, но хоть что-то. Чтобы больше сократить нужно использовать лямбды, но ты меня проклянёшь за них

2020-12-16 07:53 UTC, MMTsallagova commented on DreamEngine.Editor/EditorWindowAssetBrowser.h
> +    EditorPopupModalText* testPopupModalText;
всё убрала, кроме этого. Уже не досмотрела

2020-12-16 08:19 UTC, MMTsallagova commented on DreamEngine.Editor/EditorWindowAssetBrowser.cpp
> +       // ImGui::TreePop();
Да, я тип дерева поменяла, это от старого. Есть вариант, что я поменяю его обратно

2020-12-16 11:09 UTC, Jass2100 approved these changes

2020-12-16 12:20 UTC, nikchernyakov requested changes

2020-12-16 12:20 UTC, nikchernyakov commented on DreamEngine.Editor/EditorPopupModalNewAsset.cpp
> +            const bool is_selected = (currentType == n);
Не заметил раньше, переменная в неправильно формате названа

2020-12-16 12:27 UTC, nikchernyakov approved these changes

2020-12-16 12:28 UTC, merged