Event dispatcher for unlimited arguments
itmo-engine-team/dream-engine pull request #8
Opened 2020-09-26 17:30 UTC by Jass2100

2020-09-26 19:04 UTC, nikchernyakov requested changes

2020-09-26 19:04 UTC, nikchernyakov commented on Engine/Event.h
> +    virtual const std::string& getName() const = 0;
Публичный имена с большой буквы начинаются

2020-09-26 19:04 UTC, nikchernyakov commented on Engine/Event.h
> +    //Alias for template callback
Можешь делать плиз пробел между знаками комментария и текстом?

2020-09-26 19:04 UTC, nikchernyakov commented on Engine/Event.h
> +    const std::string& getName() const override { return this->EventName; }
Тут тоже с большой буквы должно быть

2020-09-26 19:04 UTC, nikchernyakov commented on Engine/Event.h
> +    std::string EventName;
А здесь наоборот с маленькой буквы
И ниже строчкой переменная тоже

2020-09-26 19:04 UTC, nikchernyakov commented on Engine/EventDispatcher.h
> +    std::map<std::string, std::vector<IEvent*>> EventList;
С маленькой буквы

2020-09-26 19:04 UTC, nikchernyakov commented on Engine/EventDispatcher.h
> +        auto EventIterator = EventList.find(eventName);
Локальные переменные лучше тоже с маленькой писать

2020-09-26 19:31 UTC, nikchernyakov requested changes

2020-09-26 19:31 UTC, nikchernyakov commented on Engine/Event.h
> +    const std::string& GetName() const override { return this->EventName; }
Здесь забыл EventName переименовать? Ты проверял, что оно запускается после изменений?

2020-09-26 20:13 UTC, nikchernyakov approved these changes

2020-09-26 20:13 UTC, Jass2100 commented on Engine/Event.h
> +    const std::string& GetName() const override { return this->EventName; }
Странно у меня скомпилилось, но я пофикисил

2020-09-27 07:26 UTC, MMTsallagova approved these changes

2020-09-27 10:12 UTC, merged