Init A*
itmo-engine-team/dream-engine pull request #82
Opened 2021-01-02 22:38 UTC by Jass2100

Возможно стоит подавать копию нав меша, а не сам нав меш

2021-01-03 09:48 UTC, nikchernyakov requested changes

2021-01-03 09:48 UTC, nikchernyakov commented on DreamEngine.Game.Nav/NavMesh.cpp
> +            if (polygon->Center == centerLocation)
Ну неее, это неправильно. У тебя же подаваемая точка может не совпадать с центральной точкой, да и векторы так лучше не сравнивать между собой, это же нецелые числа.
Надо выбирать полигон с наименьшим расстоянием от centerLocation до центра этого полигона

2021-01-03 09:48 UTC, nikchernyakov commented on DreamEngine.Game.Nav/NavMesh.cpp
> +    for (auto x : navMeshGrid)
Лучше конечно называть это хотя бы xRow, а то x всегда с одним числом ассоциируется

2021-01-03 09:48 UTC, nikchernyakov commented on DreamEngine.Game.Nav/PathFinding.cpp
> +        if (currentNode->Center == targetNode.Center)
Опять же лучше сравнивать индексы допустим или FirstVertexIndex для надёжности

2021-01-03 09:48 UTC, nikchernyakov commented on DreamEngine.Game.Nav/PathFinding.cpp
> +float PathFinding::euclidean(Vector3 start, Vector3 end)
У Vector3 есть функция для подсчёта расстояния насколько я помню

2021-01-03 09:48 UTC, nikchernyakov commented on DreamEngine.Game.Nav/PathFinding.cpp
> +    while (currentPolygon->Center != startNode.Center)
Здесь тоже самое про сравнение. Может быть вообще сделать внутри Polygon метод IsEquals, в котором самим определить логику сравнения

2021-01-03 09:48 UTC, nikchernyakov commented on DreamEngine.Game/Game.cpp
> +    testBox = new Actor(actorContext, new Transform({ 0, 0, 0 }));
Если что в Transform необяхательно передавать Zero вектор, он там по умолчанию стоит

2021-01-03 15:12 UTC, Jass2100 commented on DreamEngine.Game.Nav/PathFinding.cpp
> +        if (currentNode->Center == targetNode.Center)
Дак это уже сравнение нод в которые никто не изменяет, и логично сравнивать центр, а  не индексы, так как у них всегда будут одинаковые значения

2021-01-03 15:15 UTC, Jass2100 commented on DreamEngine.Game.Nav/PathFinding.cpp
> +    while (currentPolygon->Center != startNode.Center)
Опять же тут взяты полигоны которые на нав меше. Им центр никто и никогда не меняет и сравнивать их не по центру не имеет смысла. Там где мы ищем полигон там да, там нельзя сравнивать по центру, но после того как нашли полигоны, они все уже имеют константные значения

2021-01-03 15:16 UTC, Jass2100 commented on DreamEngine.Game/Game.cpp
> +    testBox = new Actor(actorContext, new Transform({ 0, 0, 0 }));
а я забыл опять убрать тестовую коробку

2021-01-03 15:16 UTC, Jass2100 commented on DreamEngine.Game.Nav/NavMesh.cpp
> +            if (polygon->Center == centerLocation)
Тут да согласен что нельзя сравнивать с центром в отличии от остальных случаев

2021-01-03 15:40 UTC, nikchernyakov commented on DreamEngine.Game.Nav/PathFinding.cpp
> +    while (currentPolygon->Center != startNode.Center)
У тебя центр состоит из трех флоатов, сравнивать которые небезопасно не через эпсилон
Индекс интовый и его точно не будут менять

2021-01-03 15:42 UTC, Jass2100 commented on DreamEngine.Game.Nav/PathFinding.cpp
> +    while (currentPolygon->Center != startNode.Center)
Дак это не безопасно в том случае если к ним имеют доступ для изменения, а тут у тебя три одинаковых флота получается которые копируют друг друга

2021-01-03 15:46 UTC, nikchernyakov commented on DreamEngine.Game.Nav/PathFinding.cpp
> +    while (currentPolygon->Center != startNode.Center)
https://ru.stackoverflow.com/questions/399420/%D0%91%D0%B5%D0%B7%D0%BE%D0%BF%D0%B0%D1%81%D0%BD%D0%BE-%D0%BB%D0%B8-%D1%81%D1%80%D0%B0%D0%B2%D0%BD%D0%B5%D0%BD%D0%B8%D0%B5-%D0%B4%D0%BB%D1%8F-%D1%82%D0%B8%D0%BF%D0%B0-double

2021-01-03 23:59 UTC, nikchernyakov requested changes

2021-01-03 23:59 UTC, nikchernyakov commented on DreamEngine.Game.Nav/NavMesh.cpp
> +            if (!canMoveByDiagonal && (x == -1 && z == -1 || x == -1 && z == 0 ||
Кажется здесь ошибка в z == 0

2021-01-03 23:59 UTC, nikchernyakov commented on DreamEngine.Game.Nav/NavMesh.cpp
> +            if (!canMoveByDiagonal && (x == -1 && z == -1 || x == -1 && z == 0 ||
А вообще достаточно всё это просто сократить условием !canMoveByDiagonal && x != 0 && z != 0

2021-01-03 23:59 UTC, nikchernyakov commented on DreamEngine.Game.Nav/NavMesh.cpp
> +            /*Vector2 leftCollisionEdge = Vector2{ worldPosition.z - collisionSize.x, worldPosition.x };
Этот комментарий ещё нужен?

2021-01-03 23:59 UTC, nikchernyakov commented on DreamEngine.Game.Nav/NavMesh.cpp
> +            if (checkPolygonCollision(worldPosition, collisionSize, polygon->Center))
Довольно простую оптимизацию можно сделать, добавив continue для полигона, если IsFree == false

2021-01-03 23:59 UTC, nikchernyakov commented on DreamEngine.Game.Nav/NavMesh.cpp
> +    while ( x < size.x)
Перед x лишний пробел

2021-01-03 23:59 UTC, nikchernyakov commented on DreamEngine.Game.Nav/NavMesh.cpp
> +    while ( x < size.x)
А зачем вообще на while это было менять? По-моему вполне симпатично смотрелось бы через for

2021-01-03 23:59 UTC, nikchernyakov commented on DreamEngine.Game.Nav/NavMesh.cpp
> +    while ( x < size.x)
Ну а вообще по факту количество индексов у тебя равно size,x/polygonSize и тогда можно продолжить считать всё через индексы только

2021-01-03 23:59 UTC, nikchernyakov commented on DreamEngine.Game.Nav/NavMesh.cpp
> +    if (downCollisionEdge.y <= polygonLocation.x && topCollisionEdge.y >= polygonLocation.x)
А это нормально, что у тебя x - это координата по вертикали от down до top, а z - по горизонтали от left до right?

2021-01-03 23:59 UTC, nikchernyakov commented on DreamEngine.Game.Nav/NavMesh.cpp
> +    Vector2 leftCollisionEdge = Vector2{ collisionPosition.z - collisionSize.x, collisionPosition.x };
Тебе достаточно считать только одно число вместо двух в векторе, потому что вторым числом ты не пользуешься. Зачем тогда создавать вектор, если можно обойтись флоатом?

2021-01-03 23:59 UTC, nikchernyakov commented on DreamEngine.Game.Nav/PathFinding.cpp
> +float PathFinding::euclidean(Vector3 start, Vector3 end)
Так а чё ты закрыл? :D

2021-01-04 15:46 UTC, Jass2100 commented on DreamEngine.Game.Nav/PathFinding.cpp
> +float PathFinding::euclidean(Vector3 start, Vector3 end)
Да уже сделано и норм считается уверен, что мы хотим на стандартную библиотеку переехать? Просто если мы вдруг поменяем на манхетена будет легче переехать.

2021-01-04 15:48 UTC, Jass2100 commented on DreamEngine.Game.Nav/NavMesh.cpp
> +            if (!canMoveByDiagonal && (x == -1 && z == -1 || x == -1 && z == 0 ||
тогда клетки по диагонали будут считаться

2021-01-04 15:48 UTC, Jass2100 commented on DreamEngine.Game.Nav/NavMesh.cpp
> +            if (!canMoveByDiagonal && (x == -1 && z == -1 || x == -1 && z == 0 ||
ТЫ по факту объединил условие на 57 и на 58

2021-01-04 15:50 UTC, Jass2100 commented on DreamEngine.Game.Nav/NavMesh.cpp
> +            if (checkPolygonCollision(worldPosition, collisionSize, polygon->Center))
дак тут мы его ниже и устанавливаем в false

2021-01-04 15:51 UTC, nikchernyakov commented on DreamEngine.Game.Nav/PathFinding.cpp
> +float PathFinding::euclidean(Vector3 start, Vector3 end)
Ну ок, просто там вызов одной функции буквально

2021-01-04 15:52 UTC, Jass2100 commented on DreamEngine.Game.Nav/NavMesh.cpp
> +    while ( x < size.x)
переехали на while потому что for не дает юзать float переменные

2021-01-04 15:55 UTC, Jass2100 commented on DreamEngine.Game.Nav/NavMesh.cpp
> +    if (downCollisionEdge.y <= polygonLocation.x && topCollisionEdge.y >= polygonLocation.x)
ну да я самого начала так начал делать когда на понг ориентировался, у меня в таком положении были координаты и я сразу про это предупредил.

2021-01-04 15:56 UTC, nikchernyakov commented on DreamEngine.Game.Nav/NavMesh.cpp
> +            if (!canMoveByDiagonal && (x == -1 && z == -1 || x == -1 && z == 0 ||
Нет не будут
У тебя клетка диагональная если обе координаты ненулевые, так что всё нормально отсекается

2021-01-04 15:56 UTC, Jass2100 commented on DreamEngine.Game.Nav/NavMesh.cpp
> +    Vector2 leftCollisionEdge = Vector2{ collisionPosition.z - collisionSize.x, collisionPosition.x };
Да тут я с прошлого кода перенёс где нужен был

2021-01-04 16:04 UTC, nikchernyakov commented on DreamEngine.Game.Nav/NavMesh.cpp
> +            if (checkPolygonCollision(worldPosition, collisionSize, polygon->Center))
Я говорю про проверку на IsFree, а не про присваивание
Если ты до проверки коллизии проверишь на IsFree, то сможешь отсечь ненужную проверку коллизии

2021-01-04 16:06 UTC, Jass2100 commented on DreamEngine.Game.Nav/NavMesh.cpp
> +            if (checkPolygonCollision(worldPosition, collisionSize, polygon->Center))
дак мы при ресете is free в true возвращаем

2021-01-04 16:59 UTC, nikchernyakov approved these changes

2021-01-04 17:01 UTC, merged